[package]
name = "nadi_core"
version = "0.2.0"
edition = "2021"
description = "Core library for Nadi systems, for use by plugins"
repository = "https://github.com/Nadi-System/nadi"
license = "GPL-3.0-only"
readme = "README.md"
keywords = ["river", "timeseries", "water-system"]
categories = ["data-structures", "science", "science::geo", "visualization"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
anyhow = "1.0.79"
chrono = { version = "0.4.34", features = ["serde"] }
csv = "1.3.0"
dot-parser = "0.1.3"
humantime-serde = "1.1.1"
itertools = "0.12.1"
serde = "1.0.196"
serde_derive = "1.0.196"
string-template-plus = "0.4.3"
toml = "0.8.9"

[build-dependencies]
rustc_version = "0.4.0"
cbindgen = "0.26.0"
